version: '3'
name: krnl
services:
  krnl-node:
    container_name: krnl-node
    build: ./node/.
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
  token-authority:
    container_name: token-authority
    build: ./token-authority/.
    ports:
      - "8181:8181"
